
const IMAGES = {
  "filmstrip": "assets/filmstrip.png",
  "elephant": "assets/elephant.png",
  "psycho": "assets/psycho.png",
  "nightmare": "assets/nightmare.png",
  "dracula": "assets/dracula.png",
  "frankenstein": "assets/frankenstein.png",
  "clockwork": "assets/clockwork.png",
  "friday": "assets/friday.png",
  "nightdead": "assets/nightdead.png",
  "texas": "assets/texas.png",
  "thing": "assets/thing.png",
  "indiana": "assets/indiana.png",
  "terminator": "assets/terminator.png",
  "deadpoets": "assets/deadpoets.png",
  "gonewind": "assets/gonewind.png",
  "jaws": "assets/jaws.png"
};
const films = [
  {title:'Psycho', year:1960, category:'Terror', format:'VHS', price:74.90, image:'psycho', poster:true, desc:'Suspense psicológico e horror clássico.'},
  {title:'A Nightmare on Elm Street', year:1984, category:'Terror', format:'VHS', price:119.90, image:'nightmare', poster:true, desc:'Terror sobrenatural que invade os sonhos.'},
  {title:'Friday the 13th', year:1980, category:'Terror', format:'VHS', price:89.90, image:'friday', poster:true, desc:'Slasher clássico da era de ouro do horror.'},
  {title:'The Texas Chain Saw Massacre', year:1974, category:'Terror', format:'VHS', price:109.90, image:'texas', poster:true, desc:'Terror brutal em uma história de sobrevivência.'},
  {title:'The Elephant Man', year:1980, category:'Drama', format:'VHS', price:89.90, image:'elephant', poster:false, desc:'Drama histórico de David Lynch.'},
  {title:'Dracula', year:1958, category:'Clássicos', format:'VHS', price:94.90, image:'dracula', poster:false, desc:'Horror gótico da Hammer Films.'},
  {title:'Frankenstein', year:1931, category:'Clássicos', format:'VHS', price:84.90, image:'frankenstein', poster:false, desc:'Um dos monstros mais marcantes do cinema.'},
  {title:'A Clockwork Orange', year:1971, category:'Clássicos', format:'FILME', price:99.90, image:'clockwork', poster:true, desc:'Ficção distópica de Stanley Kubrick.'},
  {title:'Night of the Living Dead', year:1968, category:'Terror', format:'FILME', price:79.90, image:'nightdead', poster:false, desc:'Um dos pilares do cinema de zumbis.'},
  {title:'The Thing', year:1982, category:'Ficção científica', format:'FILME', price:104.90, image:'thing', poster:true, desc:'Paranoia, isolamento e horror alienígena.'},
  {title:'Indiana Jones and the Temple of Doom', year:1984, category:'Aventura', format:'FILME', price:114.90, image:'indiana', poster:true, desc:'Aventura arqueológica em ritmo acelerado.'},
  {title:'The Terminator', year:1984, category:'Ficção científica', format:'VHS', price:99.90, image:'terminator', poster:false, desc:'Ação e ficção científica em um futuro ameaçador.'},
  {title:'Dead Poets Society', year:1989, category:'Drama', format:'FILME', price:109.90, image:'deadpoets', poster:true, desc:'Drama sobre juventude, poesia e liberdade.'},
  {title:'Gone with the Wind', year:1939, category:'Clássicos', format:'FILME', price:124.90, image:'gonewind', poster:true, desc:'Épico clássico ambientado no sul dos Estados Unidos.'},
  {title:'Jaws', year:1975, category:'Terror', format:'FILME', price:114.90, image:'jaws', poster:true, desc:'Suspense e horror marítimo dirigido por Steven Spielberg.'}
];

const homeTitles = ['Psycho','A Nightmare on Elm Street','Friday the 13th','The Texas Chain Saw Massacre'];
const posterTitles = ['Psycho','A Nightmare on Elm Street','Friday the 13th','The Texas Chain Saw Massacre','A Clockwork Orange','The Thing','Indiana Jones and the Temple of Doom','Dead Poets Society','Gone with the Wind','Jaws'];


Object.assign(IMAGES, {"django": "assets/django.png", "hellraiser": "assets/hellraiser.png", "dragon": "assets/dragon.png", "it": "assets/it.png", "omen": "assets/omen.png", "wickerman": "assets/wickerman.png", "untouchables": "assets/untouchables.png", "oz": "assets/oz.png", "dollars": "assets/dollars.png"});
films.push(...[{"title": "Django", "year": 1966, "category": "Faroeste", "format": "VHS", "price": 89.9, "image": "django", "poster": true, "desc": "Um pistoleiro misterioso chega a uma cidade dividida."}, {"title": "Hellraiser", "year": 1987, "category": "Terror", "format": "VHS", "price": 109.9, "image": "hellraiser", "poster": true, "desc": "Uma caixa enigmática abre as portas para o horror."}, {"title": "Operação Dragão", "year": 1973, "category": "Ação", "format": "VHS", "price": 99.9, "image": "dragon", "poster": true, "desc": "Bruce Lee em um clássico de artes marciais."}, {"title": "It — Uma Obra-Prima do Medo", "year": 1990, "category": "Terror", "format": "VHS", "price": 119.9, "image": "it", "poster": true, "desc": "A minissérie clássica inspirada na obra de Stephen King."}, {"title": "A Profecia", "year": 1976, "category": "Terror", "format": "VHS", "price": 94.9, "image": "omen", "poster": true, "desc": "Uma família cercada por acontecimentos sinistros."}, {"title": "O Homem de Palha", "year": 1973, "category": "Terror", "format": "VHS", "price": 104.9, "image": "wickerman", "poster": true, "desc": "Um mistério entre rituais e segredos de uma ilha."}, {"title": "Os Intocáveis", "year": 1987, "category": "Drama", "format": "VHS", "price": 109.9, "image": "untouchables", "poster": true, "desc": "Crime e investigação na Chicago da Lei Seca."}, {"title": "O Mágico de Oz", "year": 1939, "category": "Fantasia", "format": "VHS", "price": 89.9, "image": "oz", "poster": true, "desc": "Uma jornada pela estrada de tijolos amarelos."}, {"title": "Por um Punhado de Dólares", "year": 1964, "category": "Faroeste", "format": "VHS", "price": 99.9, "image": "dollars", "poster": true, "desc": "Um forasteiro entre dois grupos rivais."}]);

const imdbRatings = {"psycho": {"id": "tt0054215", "rating": 8.5, "votes": 794446}, "nightmare": {"id": "tt0087800", "rating": 7.4, "votes": 294884}, "friday": {"id": "tt0080761", "rating": 6.4, "votes": 177217}, "texas": {"id": "tt0072271", "rating": 7.4, "votes": 216072}, "elephant": {"id": "tt0080678", "rating": 8.2, "votes": 284530}, "dracula": {"id": "tt0051554", "rating": 7.2, "votes": 30272}, "frankenstein": {"id": "tt0021884", "rating": 7.7, "votes": 88730}, "clockwork": {"id": "tt0066921", "rating": 8.2, "votes": 945076}, "nightdead": {"id": "tt0063350", "rating": 7.8, "votes": 152521}, "thing": {"id": "tt0084787", "rating": 8.2, "votes": 535626}, "indiana": {"id": "tt0087469", "rating": 7.5, "votes": 573933}, "terminator": {"id": "tt0088247", "rating": 8.1, "votes": 1018531}, "deadpoets": {"id": "tt0097165", "rating": 8.1, "votes": 669435}, "gonewind": {"id": "tt0031381", "rating": 8.2, "votes": 358815}, "jaws": {"id": "tt0073195", "rating": 8.1, "votes": 750167}, "django": {"id": "tt0060315", "rating": 7.2, "votes": 34614}, "hellraiser": {"id": "tt0093177", "rating": 6.9, "votes": 155936}, "dragon": {"id": "tt0070034", "rating": 7.6, "votes": 121539}, "it": {"id": "tt0099864", "rating": 6.8, "votes": 155276}, "omen": {"id": "tt0075005", "rating": 7.5, "votes": 147823}, "wickerman": {"id": "tt0070917", "rating": 7.5, "votes": 106741}, "untouchables": {"id": "tt0094226", "rating": 7.8, "votes": 357162}, "oz": {"id": "tt0032138", "rating": 8.1, "votes": 472796}, "dollars": {"id": "tt0058461", "rating": 7.9, "votes": 256923}};
films.forEach(f => { f.imdb = imdbRatings[f.image]; });

Object.assign(IMAGES, {"kingkong": "assets/kingkong.png", "casablanca": "assets/casablanca.png", "wonderful": "assets/wonderful.png", "indemnity": "assets/indemnity.png", "kane": "assets/kane.png", "angrymen": "assets/angrymen.png", "samurai": "assets/samurai.png", "tokyo": "assets/tokyo.png", "platoon": "assets/platoon.png"});
Object.assign(imdbRatings, {"kingkong": {"id": "tt0024216", "rating": 7.9, "votes": 96666}, "casablanca": {"id": "tt0034583", "rating": 8.5, "votes": 661185}, "wonderful": {"id": "tt0038650", "rating": 8.6, "votes": 559566}, "indemnity": {"id": "tt0036775", "rating": 8.3, "votes": 183330}, "kane": {"id": "tt0033467", "rating": 8.2, "votes": 496841}, "angrymen": {"id": "tt0050083", "rating": 9.0, "votes": 1003288}, "samurai": {"id": "tt0047478", "rating": 8.6, "votes": 405879}, "tokyo": {"id": "tt0046438", "rating": 8.1, "votes": 78866}, "platoon": {"id": "tt0091763", "rating": 8.0, "votes": 477210}});
films.push(...[{"title": "King Kong", "year": 1933, "category": "Aventura", "format": "FILME", "price": 94.9, "desc": "Uma expedição encontra uma criatura lendária em uma ilha desconhecida.", "image": "kingkong", "poster": true, "aliases": "King Kong", "imdb": {"id": "tt0024216", "rating": 7.9, "votes": 96666}}, {"title": "Casablanca", "year": 1942, "category": "Romance", "format": "VHS", "price": 99.9, "desc": "Um reencontro coloca o amor e o dever em lados opostos.", "image": "casablanca", "poster": true, "aliases": "Casablanca", "imdb": {"id": "tt0034583", "rating": 8.5, "votes": 661185}}, {"title": "A Felicidade Não se Compra", "year": 1946, "category": "Fantasia", "format": "FILME", "price": 94.9, "desc": "Um homem descobre o impacto de sua vida nas pessoas ao redor.", "image": "wonderful", "poster": true, "aliases": "It's a Wonderful Life", "imdb": {"id": "tt0038650", "rating": 8.6, "votes": 559566}}, {"title": "Pacto de Sangue", "year": 1944, "category": "Noir", "format": "FILME", "price": 104.9, "desc": "Sedução, ambição e um plano de seguro que leva ao crime.", "image": "indemnity", "poster": true, "aliases": "Double Indemnity", "imdb": {"id": "tt0036775", "rating": 8.3, "votes": 183330}}, {"title": "Cidadão Kane", "year": 1941, "category": "Drama", "format": "FILME", "price": 109.9, "desc": "Uma investigação reconstrói a vida de um poderoso magnata da imprensa.", "image": "kane", "poster": true, "aliases": "Citizen Kane", "imdb": {"id": "tt0033467", "rating": 8.2, "votes": 496841}}, {"title": "12 Homens e uma Sentença", "year": 1957, "category": "Drama", "format": "VHS", "price": 99.9, "desc": "Doze jurados debatem uma decisão capaz de mudar uma vida.", "image": "angrymen", "poster": true, "aliases": "12 Angry Men", "imdb": {"id": "tt0050083", "rating": 9.0, "votes": 1003288}}, {"title": "Os Sete Samurais", "year": 1954, "category": "Ação", "format": "FILME", "price": 124.9, "desc": "Samurais unem forças para defender uma aldeia ameaçada por bandidos.", "image": "samurai", "poster": true, "aliases": "Seven Samurai Shichinin no samurai", "imdb": {"id": "tt0047478", "rating": 8.6, "votes": 405879}}, {"title": "Era uma Vez em Tóquio", "year": 1953, "category": "Drama", "format": "FILME", "price": 104.9, "desc": "A visita de um casal aos filhos revela a distância entre gerações.", "image": "tokyo", "poster": true, "aliases": "Tokyo Story Tokyo monogatari", "imdb": {"id": "tt0046438", "rating": 8.1, "votes": 78866}}, {"title": "Platoon", "year": 1986, "category": "Guerra", "format": "VHS", "price": 109.9, "desc": "Um jovem soldado enfrenta os conflitos e a brutalidade da Guerra do Vietnã.", "image": "platoon", "poster": true, "aliases": "Platoon", "imdb": {"id": "tt0091763", "rating": 8.0, "votes": 477210}}]);
